name: Build and Deploy Code

on:
  push:
    branches: ["development"]

jobs:
  build:
    environment:
      name: portfolio
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: set up python v3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing all dependencies
        run: pip install -r requirements/unfrozen.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest -v -s